### ISSUE TITLE
AWS Doc Format Changed

### ISSUE THREAD

**Issue by phene** [pdhodgkinson/AWSCloudFormationTemplateReference-dash-docset#4]
The structure of the CloudFormation documentation has fundamentally changed and this no longer works.

**Comment by majwhite** [comment]
@phene - I have raised a PR that switches the script to use the JSON file that the CloudFormation Documentation website is now using to drive the menu that points to all the Documentation. (https://github.com/pdhodgkinson/AWSCloudFormationTemplateReference-dash-docset/pull/5).

**Comment by pdhodgkinson** [comment]
Yep, should be fixed now, thanks to @majwhite
